CREATE TABLE  "AMBIENTE" 
   (	"ID" NUMBER(20,0) NOT NULL ENABLE, 
	"FECHA" TIMESTAMP (6) NOT NULL ENABLE, 
	"LATITUD" NUMBER NOT NULL ENABLE, 
	"LONGITUD" NUMBER NOT NULL ENABLE, 
	"MQ7" NUMBER(10,5) NOT NULL ENABLE, 
	"MQ135" NUMBER(10,5) NOT NULL ENABLE, 
	"GUVAS12SDUV" NUMBER(10,5) NOT NULL ENABLE, 
	 CONSTRAINT "AMBIENTE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE OR REPLACE EDITIONABLE FUNCTION  "DISTANCIA_MAPA" (LATITUD1 NUMBER, LONGITUD1 NUMBER, LATITUD2 NUMBER, LONGITUD2 NUMBER)
RETURN NUMBER
IS
  RADLAT1   NUMBER;
  RADLAT2   NUMBER;
  RADLONG1  NUMBER;
  RADLONG2  NUMBER;
  RADIO     NUMBER;
  PI        NUMBER;
  ------------------
BEGIN
  PI        := 3.14159265359;
  RADIO     := 6371;
  RADLAT1   := LATITUD1 * PI / 180;
  RADLAT2   := LATITUD2 * PI / 180;
  RADLONG1  := LONGITUD1 * PI / 180;
  RADLONG2  := LONGITUD2 * PI / 180;
  
  RETURN ACOS(SIN(RADLAT1) * SIN(RADLAT2) + COS(RADLAT1) * COS(RADLAT2) * COS(RADLONG1 - RADLONG2)) * RADIO;
END DISTANCIA_MAPA;
/

CREATE INDEX  "IDX_AMBIENTE_FECHA" ON  "AMBIENTE" ("FECHA")
/
 CREATE SEQUENCE   "AMBIENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3001 CACHE 20 NOORDER  NOCYCLE  NOPARTITION
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_AMBIENTE" 
  before insert on "AMBIENTE"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "AMBIENTE_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
  --Fecha
  if :NEW."FECHA" is null then 
    select SYSTIMESTAMP into :NEW."FECHA" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_AMBIENTE" ENABLE
/
CREATE OR REPLACE FORCE EDITIONABLE VIEW  "VW_AMBIENTE" ("FECHA", "HORA", "LATITUD", "LONGITUD", "MQ7", "MQ135", "GUVAS12SDUV") AS 
  SELECT  TRUNC(FECHA - INTERVAL '6' HOUR) AS FECHA
      , TO_NUMBER(TO_CHAR(FECHA - INTERVAL '6' HOUR, 'HH24')) AS HORA
      , LATITUD
      , LONGITUD
      , MQ7
      , MQ135
      , GUVAS12SDUV 
 FROM AMBIENTE
ORDER BY ID
/
